# Generated by Django 5.1.4 on 2025-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
