# Generated by Django 5.1.6 on 2025-02-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_todo_created_at_todo_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Status',
        ),
    ]
