# Generated by Django 5.1.6 on 2025-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
